function schema
%SCHEMA  Defines properties for @simplot class (MPC simulation data)

%  Author(s): James G. owen
%  Copyright 1986-2007 The MathWorks, Inc.
%  $Revision: 1.1.6.3 $ $Date: 2007/11/09 20:46:36 $

% Find parent package
pkg = findpackage('mpcobjects');
parentpkg = findpackage('resppack');

% Register class (subclass)
c = schema.class(pkg, 'simplot', findclass(parentpkg, 'simplot'));

% Enumerations
if isempty(findtype('MPCPlotType'))
    schema.EnumType('MPCPlotType', {'inputs', 'outputs'});
end

% Properties
p = schema.prop(c,'Type','MPCPlotType');
p.FactoryValue = 'outputs';
% Apprdata property is a struct used to group plots generated by the same
% generated by the same simulation task so that they can find eachother.
schema.prop(c,'Appdata','MATLAB array');
